// Coverage ported from the deleted src/app/sitemap.test.ts and
// src/app/sitemap-products.xml/route.test.ts when the sitemaps moved from
// serverless routes to committed static files generated by
// scripts/generate_sitemaps.mjs.
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  buildSitemapIndexXml,
  buildSitemapUrlsetXml,
  countLocs,
  parseLastmod,
  productUrlEntries,
  readCanonicalProduct,
  sitemapCountGuard,
  sitemapIndexEntries,
  staticSitemapEntries,
} from './sitemap_lib.mjs'
import { collectSitemapProducts } from './generate_sitemaps.mjs'

const STATIC_URLS = ['https://agent.pivota.cc', 'https://agent.pivota.cc/products']

function locs(xml) {
  return Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g), (match) => match[1])
}

function canonicalProduct(id, updatedAt = '2026-05-01T12:00:00.000Z') {
  const row = {
    sig_id: id,
    content_key: `ck_${id.replace(/^sig_/, '')}`,
    serving_eligible: true,
  }
  if (updatedAt !== null) row.updated_at = updatedAt
  return row
}

function products(count, prefix = 'sig_mock_product') {
  return Array.from({ length: count }, (_, index) =>
    canonicalProduct(`${prefix}_${String(index).padStart(4, '0')}`),
  )
}

function pageResponse(items, total, offset = 0, extra = {}) {
  return new Response(JSON.stringify({ items, total, limit: 1000, offset, ...extra }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  })
}

describe('sitemap index entries', () => {
  it('points crawlers to static and product sitemaps', () => {
    expect(sitemapIndexEntries().map((e) => e.loc)).toEqual([
      'https://agent.pivota.cc/sitemap-static.xml',
      'https://agent.pivota.cc/sitemap-products.xml',
    ])
  })

  it('omits <lastmod> on index entries (children carry their own)', () => {
    for (const entry of sitemapIndexEntries()) {
      expect(entry.lastmod).toBeUndefined()
    }
  })

  it('builds valid sitemap index XML', () => {
    const xml = buildSitemapIndexXml(sitemapIndexEntries())

    expect(xml).toContain('<?xml version="1.0" encoding="UTF-8"?>')
    expect(xml).toContain('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    expect(xml).not.toContain('<lastmod>')
    expect(locs(xml)).toEqual([
      'https://agent.pivota.cc/sitemap-static.xml',
      'https://agent.pivota.cc/sitemap-products.xml',
    ])
  })
})

describe('static urlset', () => {
  it('emits only public static app URLs', () => {
    const urls = staticSitemapEntries().map((e) => e.loc)

    expect(urls).toEqual(STATIC_URLS)
    expect(urls).not.toContain('https://agent.pivota.cc/order')
    expect(urls.some((url) => /\/products\/sig_/.test(url))).toBe(false)
  })

  it('keeps crawler-friendly freshness hints for static routes', () => {
    const entries = staticSitemapEntries()

    expect(entries.find((e) => e.loc === 'https://agent.pivota.cc')?.changefreq).toBe('daily')
    expect(entries.find((e) => e.loc === 'https://agent.pivota.cc/products')?.priority).toBe(0.9)
  })

  it('omits <lastmod> on static entries (no real change signal for / or /products)', () => {
    const xml = buildSitemapUrlsetXml(staticSitemapEntries())

    expect(xml).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    expect(xml).not.toContain('<lastmod>')
    expect(locs(xml)).toEqual(STATIC_URLS)
  })
})

describe('product row parsing (eligibility, identity, lastmod)', () => {
  it('filters non-sig rows, non-eligible rows, and rows missing content_key', () => {
    const rows = [
      canonicalProduct('sig_keep_me'),
      { sig_id: 'ext_alias' },
      { sig_id: 'sig_missing_eligibility', content_key: 'ck_missing_eligibility' },
      { sig_id: 'sig_missing_content_key', serving_eligible: true },
      { sig_id: 'sig_blocked', serving_eligible: false },
      { sig_id: 'sig_also_blocked', is_indexable: 'false' },
      null,
      'not-an-object',
    ]

    const kept = rows.map(readCanonicalProduct).filter(Boolean)
    expect(kept.map((p) => p.id)).toEqual(['sig_keep_me'])
  })

  it('includes offer-free index_eligible rows keyed on content_key (store-less brands)', () => {
    const storeless = readCanonicalProduct({
      sig_id: null,
      content_key: 'ck_storeless_brand',
      serving_eligible: false,
      index_eligible: true,
      updated_at: '2026-05-01T12:00:00.000Z',
    })
    const buyable = readCanonicalProduct(canonicalProduct('sig_buyable'))
    const noIdentity = readCanonicalProduct({ sig_id: null, index_eligible: true })

    expect(storeless?.id).toBe('ck_storeless_brand')
    expect(buyable?.id).toBe('sig_buyable')
    expect(noIdentity).toBeNull()
  })

  it('omits <lastmod> when a row has no updated_at (no fabricated timestamps)', () => {
    const withTs = readCanonicalProduct(canonicalProduct('sig_with_timestamp'))
    const withoutTs = readCanonicalProduct(canonicalProduct('sig_no_timestamp', null))

    const xml = buildSitemapUrlsetXml(productUrlEntries([withTs, withoutTs]))
    const withBlock = xml.match(
      /<url>\s*<loc>https:\/\/agent\.pivota\.cc\/products\/sig_with_timestamp<\/loc>[\s\S]*?<\/url>/,
    )
    const withoutBlock = xml.match(
      /<url>\s*<loc>https:\/\/agent\.pivota\.cc\/products\/sig_no_timestamp<\/loc>[\s\S]*?<\/url>/,
    )

    expect(withBlock?.[0]).toContain('<lastmod>2026-05-01T12:00:00.000Z</lastmod>')
    expect(withoutBlock?.[0]).not.toContain('<lastmod>')
    expect(xml).toContain('<changefreq>weekly</changefreq>')
  })

  it('parses bare timestamps as UTC and rejects garbage', () => {
    expect(parseLastmod('2026-05-01T12:00:00')?.toISOString()).toBe('2026-05-01T12:00:00.000Z')
    expect(parseLastmod('2026-05-01T12:00:00.000Z')?.toISOString()).toBe(
      '2026-05-01T12:00:00.000Z',
    )
    expect(parseLastmod('')).toBeNull()
    expect(parseLastmod(undefined)).toBeNull()
    expect(parseLastmod('not-a-date')).toBeNull()
  })
})

describe('collectSitemapProducts — backend pagination', () => {
  beforeEach(() => {
    vi.stubEnv('PIVOTA_BACKEND_BASE_URL', 'https://canonical.example.com')
  })

  afterEach(() => {
    vi.restoreAllMocks()
    vi.unstubAllEnvs()
  })

  it('paginates canonical products until the endpoint is exhausted and dedupes', async () => {
    const firstPage = products(1000, 'sig_page_one')
    const secondPage = [canonicalProduct('sig_page_two_0000'), canonicalProduct('sig_page_one_0000')]
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const offset = new URL(String(input)).searchParams.get('offset')
      return pageResponse(offset === '0' ? firstPage : secondPage, 1002, Number(offset || 0))
    })

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(2)
    expect(new URL(String(fetchMock.mock.calls[0][0])).searchParams.get('offset')).toBe('0')
    expect(new URL(String(fetchMock.mock.calls[1][0])).searchParams.get('offset')).toBe('1000')
    const fetchedUrl = new URL(String(fetchMock.mock.calls[0][0]))
    expect(fetchedUrl.pathname).toBe('/api/canonical/products')
    expect(fetchedUrl.searchParams.get('limit')).toBe('1000')
    // duplicate sig_page_one_0000 dropped
    expect(collected).toHaveLength(1001)
    expect(source).toBe('serving_eligible')
    const ids = collected.map((p) => p.id)
    expect(ids).toContain('sig_page_one_0000')
    expect(ids).toContain('sig_page_two_0000')
    // deterministic output: sorted by id regardless of backend order
    expect(ids).toEqual([...ids].sort())
  })

  it('reports serving_eligible_partial when rows are filtered out', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse([canonicalProduct('sig_keep_me'), { sig_id: 'ext_alias' }], 2),
    )

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected.map((p) => p.id)).toEqual(['sig_keep_me'])
    expect(source).toBe('serving_eligible_partial')
  })

  it('pages by keyset cursor when the backend provides next_cursor', async () => {
    const firstPage = products(1000, 'sig_cursor_one')
    const secondPage = [canonicalProduct('sig_cursor_two_0000')]
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const url = new URL(String(input))
      if (url.searchParams.get('cursor') === 'opaque-cursor-1') {
        return pageResponse(secondPage, null, 0, { has_more: false, next_cursor: null })
      }
      return pageResponse(firstPage, 1001, 0, {
        has_more: true,
        next_cursor: 'opaque-cursor-1',
      })
    })

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(2)
    const firstUrl = new URL(String(fetchMock.mock.calls[0][0]))
    expect(firstUrl.searchParams.get('offset')).toBe('0')
    expect(firstUrl.searchParams.get('cursor')).toBeNull()
    const secondUrl = new URL(String(fetchMock.mock.calls[1][0]))
    expect(secondUrl.searchParams.get('cursor')).toBe('opaque-cursor-1')
    // Cursor and offset are mutually exclusive on the backend.
    expect(secondUrl.searchParams.get('offset')).toBeNull()
    expect(collected).toHaveLength(1001)
    expect(source).toBe('serving_eligible')
  })

  it('stops on has_more=false even when the page is full and total is null', async () => {
    // New backend, catalog exactly one page: total present only on page one,
    // has_more says stop. The legacy full-page heuristic alone would have
    // issued a wasted second fetch.
    const fetchMock = vi
      .spyOn(globalThis, 'fetch')
      .mockResolvedValueOnce(
        pageResponse(products(1000), 1000, 0, { has_more: false, next_cursor: null }),
      )

    const { products: collected } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(collected).toHaveLength(1000)
  })

  it('falls back to offset paging when next_cursor stops mid-crawl', async () => {
    // Defensive backend path: has_more=true but no cursor. The crawl must
    // continue from the rows already consumed, not restart at offset=0.
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const url = new URL(String(input))
      const offset = url.searchParams.get('offset')
      if (offset === '0') {
        return pageResponse(products(1000, 'sig_fb_one'), null, 0, {
          has_more: true,
          next_cursor: null,
        })
      }
      return pageResponse([canonicalProduct('sig_fb_two_0000')], null, 1000, {
        has_more: false,
        next_cursor: null,
      })
    })

    const { products: collected } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(2)
    expect(new URL(String(fetchMock.mock.calls[1][0])).searchParams.get('offset')).toBe('1000')
    expect(collected).toHaveLength(1001)
  })

  it('offset-resume anchor tracks rows consumed, not the nominal page size', async () => {
    // The failure this guards: cursor paging, then next_cursor drops on a
    // SHORT page (fewer items than `limit`) while has_more stays true. The
    // offset fallback must resume at the exact count of rows already consumed
    // (1000 + 400 = 1400), NOT `offset += limit` (which would jump to 2000 and
    // silently skip 600 rows — an undercount small enough to slip past the
    // 50%-shrink guard).
    const calls = []
    vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const url = new URL(String(input))
      const cursor = url.searchParams.get('cursor')
      const offset = url.searchParams.get('offset')
      calls.push({ cursor, offset })
      if (cursor === null && offset === '0') {
        return pageResponse(products(1000, 'sig_anchor_a'), null, 0, {
          has_more: true,
          next_cursor: 'CUR1',
        })
      }
      if (cursor === 'CUR1') {
        // Short page + downgrade: has_more true, no next_cursor.
        return pageResponse(products(400, 'sig_anchor_b'), null, 0, {
          has_more: true,
          next_cursor: null,
        })
      }
      // Resume-by-offset page: the offset it arrives with is the assertion.
      return pageResponse(products(2, 'sig_anchor_c'), null, Number(offset), {
        has_more: false,
        next_cursor: null,
      })
    })

    const { products: collected } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    // Page 3 resumed at rows consumed (1000 + 400), not at offset += limit.
    expect(calls).toHaveLength(3)
    expect(calls[1]).toEqual({ cursor: 'CUR1', offset: null })
    expect(calls[2]).toEqual({ cursor: null, offset: '1400' })
    // Full set collected, no gaps and no duplicates.
    expect(collected).toHaveLength(1402)
    expect(new Set(collected.map((p) => p.id)).size).toBe(1402)
  })

  it('returns an empty set when the endpoint has no products', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(pageResponse([], 0))

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected).toHaveLength(0)
    expect(source).toBe('serving_eligible')
    const xml = buildSitemapUrlsetXml(productUrlEntries(collected))
    expect(xml).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    expect(xml).not.toContain('<url>')
  })
})

describe('sanity guard — never publish a stub over the full set (#219/#223 lesson)', () => {
  it('refuses counts below the absolute floor', () => {
    expect(sitemapCountGuard(0, null)).toMatch(/absolute floor/)
    expect(sitemapCountGuard(999, null)).toMatch(/absolute floor/)
    expect(sitemapCountGuard(1000, null)).toBeNull()
  })

  it('refuses a large shrink vs the committed count', () => {
    expect(sitemapCountGuard(3000, 7400)).toMatch(/less than 50%/)
    expect(sitemapCountGuard(3700, 7400)).toBeNull()
    expect(sitemapCountGuard(7400, 7400)).toBeNull()
  })

  it('ignores the ratio check when there is no committed file', () => {
    expect(sitemapCountGuard(1200, null)).toBeNull()
  })

  it('counts <loc> entries in existing XML', () => {
    const xml = buildSitemapUrlsetXml(productUrlEntries([
      readCanonicalProduct(canonicalProduct('sig_a')),
      readCanonicalProduct(canonicalProduct('sig_b')),
    ]))
    expect(countLocs(xml)).toBe(2)
  })
})

describe('deterministic observability comment', () => {
  it('embeds source and count as an XML comment after the declaration', () => {
    const xml = buildSitemapUrlsetXml(
      productUrlEntries([readCanonicalProduct(canonicalProduct('sig_a'))]),
      'source=serving_eligible urls=1',
    )

    expect(xml).toMatch(
      /^<\?xml version="1\.0" encoding="UTF-8"\?>\n<!-- source=serving_eligible urls=1 -->\n<urlset/,
    )
  })
})
