// Coverage ported from the deleted src/app/sitemap.test.ts and
// src/app/sitemap-products.xml/route.test.ts when the sitemaps moved from
// serverless routes to committed static files generated by
// scripts/generate_sitemaps.mjs.
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  buildSitemapIndexXml,
  buildSitemapUrlsetXml,
  countLocs,
  mergeDuplicateProduct,
  parseLastmod,
  parseSitemapProductIds,
  preferSitemapId,
  productUrlEntries,
  readCanonicalProduct,
  sitemapCountGuard,
  sitemapCoverageGuard,
  sitemapIdGuard,
  sitemapIndexEntries,
  staticSitemapEntries,
} from './sitemap_lib.mjs'
import { collectSitemapProducts } from './generate_sitemaps.mjs'

const STATIC_URLS = ['https://agent.pivota.cc', 'https://agent.pivota.cc/products']

function locs(xml) {
  return Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g), (match) => match[1])
}

function canonicalProduct(id, updatedAt = '2026-05-01T12:00:00.000Z') {
  const row = {
    sig_id: id,
    content_key: `ck_${id.replace(/^sig_/, '')}`,
    serving_eligible: true,
  }
  if (updatedAt !== null) row.updated_at = updatedAt
  return row
}

function products(count, prefix = 'sig_mock_product') {
  return Array.from({ length: count }, (_, index) =>
    canonicalProduct(`${prefix}_${String(index).padStart(4, '0')}`),
  )
}

function pageResponse(items, total, offset = 0, extra = {}) {
  return new Response(JSON.stringify({ items, total, limit: 1000, offset, ...extra }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  })
}

describe('sitemap index entries', () => {
  it('points crawlers to static and product sitemaps', () => {
    expect(sitemapIndexEntries().map((e) => e.loc)).toEqual([
      'https://agent.pivota.cc/sitemap-static.xml',
      'https://agent.pivota.cc/sitemap-products.xml',
    ])
  })

  it('omits <lastmod> on index entries (children carry their own)', () => {
    for (const entry of sitemapIndexEntries()) {
      expect(entry.lastmod).toBeUndefined()
    }
  })

  it('builds valid sitemap index XML', () => {
    const xml = buildSitemapIndexXml(sitemapIndexEntries())

    expect(xml).toContain('<?xml version="1.0" encoding="UTF-8"?>')
    expect(xml).toContain('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    expect(xml).not.toContain('<lastmod>')
    expect(locs(xml)).toEqual([
      'https://agent.pivota.cc/sitemap-static.xml',
      'https://agent.pivota.cc/sitemap-products.xml',
    ])
  })
})

describe('static urlset', () => {
  it('emits only public static app URLs', () => {
    const urls = staticSitemapEntries().map((e) => e.loc)

    expect(urls).toEqual(STATIC_URLS)
    expect(urls).not.toContain('https://agent.pivota.cc/order')
    expect(urls.some((url) => /\/products\/sig_/.test(url))).toBe(false)
  })

  it('keeps crawler-friendly freshness hints for static routes', () => {
    const entries = staticSitemapEntries()

    expect(entries.find((e) => e.loc === 'https://agent.pivota.cc')?.changefreq).toBe('daily')
    expect(entries.find((e) => e.loc === 'https://agent.pivota.cc/products')?.priority).toBe(0.9)
  })

  it('omits <lastmod> on static entries (no real change signal for / or /products)', () => {
    const xml = buildSitemapUrlsetXml(staticSitemapEntries())

    expect(xml).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    expect(xml).not.toContain('<lastmod>')
    expect(locs(xml)).toEqual(STATIC_URLS)
  })
})

describe('product row parsing (eligibility, identity, lastmod)', () => {
  it('filters non-sig rows, non-eligible rows, and rows missing content_key', () => {
    const rows = [
      canonicalProduct('sig_keep_me'),
      { sig_id: 'ext_alias' },
      { sig_id: 'sig_missing_eligibility', content_key: 'ck_missing_eligibility' },
      { sig_id: 'sig_missing_content_key', serving_eligible: true },
      { sig_id: 'sig_blocked', serving_eligible: false },
      { sig_id: 'sig_also_blocked', is_indexable: 'false' },
      null,
      'not-an-object',
    ]

    const kept = rows.map(readCanonicalProduct).filter(Boolean)
    expect(kept.map((p) => p.id)).toEqual(['sig_keep_me'])
  })

  it('drops ck-keyed rows with no minted sig — those URLs 500 in production', () => {
    // Regression guard. The old fallback `sig.startsWith('sig_') ? sig : contentKey`
    // advertised /products/ck_… for store-less brand rows, on the assumption that
    // both id forms resolve. They do not: verified 2026-07-25, ALL 7 ck-keyed URLs
    // in the live sitemap returned 500 (get_pdp_v2 rejects a bare content_key with
    // MISSING_MERCHANT_CONTEXT). A sitemap must never advertise a URL that errors.
    const ckOnly = readCanonicalProduct({
      content_key: 'ck_no_sig_minted',
      serving_eligible: true,
    })
    const ckOnlyIndexable = readCanonicalProduct({
      content_key: 'ck_citation_row',
      index_eligible: true,
    })

    expect(ckOnly).toBeNull()
    expect(ckOnlyIndexable).toBeNull()
    // …and a proper sig row is unaffected.
    expect(readCanonicalProduct(canonicalProduct('sig_ok'))?.id).toBe('sig_ok')
  })

  it('drops sig rows the backend marks renderable=false (dead-PDP shells)', () => {
    const dead = readCanonicalProduct({ ...canonicalProduct('sig_dead'), renderable: false })
    const live = readCanonicalProduct({ ...canonicalProduct('sig_live'), renderable: true })

    expect(dead).toBeNull()
    expect(live?.id).toBe('sig_live')
  })

  it('keeps rows when renderable is absent (backend predating the field)', () => {
    // Fail-open on ABSENCE only: an older backend must reproduce the
    // pre-fix sitemap, not an empty one. Explicit false still drops.
    const legacy = readCanonicalProduct(canonicalProduct('sig_legacy'))
    expect(legacy?.id).toBe('sig_legacy')
  })

  it('ck-keyed rows are dropped before the renderable gate is reached', () => {
    // Previously exempt from the renderable gate (renderable is only defined for
    // sig PDPs). Now moot: ck-keyed rows are rejected earlier for lacking a sig,
    // so neither renderable=false nor an absent flag can readmit them.
    expect(readCanonicalProduct({
      content_key: 'ck_citation', index_eligible: true, renderable: false,
    })).toBeNull()
    expect(readCanonicalProduct({
      content_key: 'ck_citation2', index_eligible: true,
    })).toBeNull()
  })

  it('WITHHOLDS offer-free ck-keyed rows while /products/{ck} 500s (was: included)', () => {
    // This encoded a real feature: store-less brands with no minted sig were
    // published for offer-free citation at /products/{content_key}. The feature
    // is DISABLED here, not deleted, because it is 100% broken in production —
    // all 7 such URLs in the live sitemap returned 500 on 2026-07-25 (get_pdp_v2
    // rejects a bare content_key: MISSING_MERCHANT_CONTEXT). A sitemap that
    // advertises 500s spends crawl budget on errors and signals an unhealthy
    // domain, which is strictly worse than omitting the rows.
    //
    // TO RESTORE: make the backend resolve a bare ck_ (or mint sigs for these
    // rows), verify /products/{ck} returns 200, then re-allow the ck fallback in
    // readCanonicalProduct and flip these expectations back.
    const storeless = readCanonicalProduct({
      sig_id: null,
      content_key: 'ck_storeless_brand',
      serving_eligible: false,
      index_eligible: true,
      updated_at: '2026-05-01T12:00:00.000Z',
    })
    const buyable = readCanonicalProduct(canonicalProduct('sig_buyable'))
    const noIdentity = readCanonicalProduct({ sig_id: null, index_eligible: true })

    expect(storeless).toBeNull()
    expect(buyable?.id).toBe('sig_buyable')
    expect(noIdentity).toBeNull()
  })

  it('omits <lastmod> when a row has no updated_at (no fabricated timestamps)', () => {
    const withTs = readCanonicalProduct(canonicalProduct('sig_with_timestamp'))
    const withoutTs = readCanonicalProduct(canonicalProduct('sig_no_timestamp', null))

    const xml = buildSitemapUrlsetXml(productUrlEntries([withTs, withoutTs]))
    const withBlock = xml.match(
      /<url>\s*<loc>https:\/\/agent\.pivota\.cc\/products\/sig_with_timestamp<\/loc>[\s\S]*?<\/url>/,
    )
    const withoutBlock = xml.match(
      /<url>\s*<loc>https:\/\/agent\.pivota\.cc\/products\/sig_no_timestamp<\/loc>[\s\S]*?<\/url>/,
    )

    expect(withBlock?.[0]).toContain('<lastmod>2026-05-01T12:00:00.000Z</lastmod>')
    expect(withoutBlock?.[0]).not.toContain('<lastmod>')
    expect(xml).toContain('<changefreq>weekly</changefreq>')
  })

  it('parses bare timestamps as UTC and rejects garbage', () => {
    expect(parseLastmod('2026-05-01T12:00:00')?.toISOString()).toBe('2026-05-01T12:00:00.000Z')
    expect(parseLastmod('2026-05-01T12:00:00.000Z')?.toISOString()).toBe(
      '2026-05-01T12:00:00.000Z',
    )
    expect(parseLastmod('')).toBeNull()
    expect(parseLastmod(undefined)).toBeNull()
    expect(parseLastmod('not-a-date')).toBeNull()
  })
})

describe('one URL per product — content_key dedup (identity fragmentation)', () => {
  const sig24a = `sig_${'a'.repeat(24)}`
  const sig24b = `sig_${'b'.repeat(24)}`
  const sig32a = `sig_${'a'.repeat(32)}`
  const sig32b = `sig_${'b'.repeat(32)}`

  it('prefers 32-hex content sigs over 24-hex, then lexicographic; any sig over the ck fallback', () => {
    expect(preferSitemapId(sig24a, sig32b)).toBe(sig32b)
    expect(preferSitemapId(sig32b, sig24a)).toBe(sig32b)
    expect(preferSitemapId(sig32b, sig32a)).toBe(sig32a)
    expect(preferSitemapId('ck_storeless', sig24b)).toBe(sig24b)
    // symmetric: argument order must not change the winner
    expect(preferSitemapId(sig24b, 'ck_storeless')).toBe(sig24b)
  })

  it('merges duplicate sigs for one content_key: preferred id + max lastmod, no fabrication', () => {
    const older = { id: sig24a, contentKey: 'ck_dup', lastmod: new Date('2026-01-01T00:00:00Z') }
    const newer = { id: sig32b, contentKey: 'ck_dup', lastmod: new Date('2026-06-01T00:00:00Z') }
    const merged = mergeDuplicateProduct(older, newer)
    expect(merged.id).toBe(sig32b)
    expect(merged.contentKey).toBe('ck_dup')
    expect(merged.lastmod).toEqual(new Date('2026-06-01T00:00:00Z'))

    // one side missing lastmod → keep the known one; both missing → undefined-ish
    expect(mergeDuplicateProduct({ ...older, lastmod: null }, newer).lastmod).toEqual(
      new Date('2026-06-01T00:00:00Z'),
    )
    expect(mergeDuplicateProduct({ ...older, lastmod: null }, { ...newer, lastmod: null }).lastmod).toBeNull()
  })
})

describe('incumbency — an advertised URL is never swapped for an equivalent sibling', () => {
  // The P3 shape (pivota-backend#1585 / PIVOTA-Agent#1828, 2026-07-25): a
  // Path-C minted sig and the external_seed mirror sig it was minted from share
  // one content_key and render byte-equivalent PDPs. Only the mirror is in the
  // committed sitemap, because the minted row was renderable=false when it was
  // generated. Measured in prod: 441 such pairs now arrive with BOTH sigs
  // eligible, and hex/lexicographic order alone hands 183 of them to the fresh
  // minted sig — replacing an indexed URL with a brand-new one.
  //
  // Hex values match generate_sitemaps.incumbency.test.mjs so the same pair
  // means the same thing in both files: the MINTED sig wins the pure ordering,
  // which is the only direction in which an incumbency bug can show up.
  const mirrorSig = `sig_${'f'.repeat(32)}`
  const mintedSig = `sig_${'0'.repeat(32)}`

  it('extracts the advertised product ids from a committed sitemap', () => {
    const xml = buildSitemapUrlsetXml([
      { loc: `https://agent.pivota.cc/products/${mirrorSig}` },
      { loc: `https://agent.pivota.cc/products/${mintedSig}` },
      // Non-product locs (the static sitemap's entries) must not leak in.
      { loc: 'https://agent.pivota.cc' },
      { loc: 'https://agent.pivota.cc/products' },
      // A foreign host is not one of our incumbents either.
      { loc: 'https://example.com/products/sig_notours' },
    ])
    expect(parseSitemapProductIds(xml)).toEqual(new Set([mirrorSig, mintedSig]))
  })

  it('round-trips a percent-encoded id so it still matches its product', () => {
    // productUrlEntries encodes the id; the incumbent set must decode it back
    // or an id containing ':' would never match itself run-to-run.
    const encoded = buildSitemapUrlsetXml(productUrlEntries([{ id: 'sig_a:b', lastmod: null }]))
    expect(encoded).toContain('/products/sig_a%3Ab')
    expect(parseSitemapProductIds(encoded)).toEqual(new Set(['sig_a:b']))
  })

  it('returns no incumbents for an absent or non-sitemap file (degrades to the pure order)', () => {
    expect(parseSitemapProductIds('')).toEqual(new Set())
    expect(parseSitemapProductIds(undefined)).toEqual(new Set())
    expect(parseSitemapProductIds('<urlset></urlset>')).toEqual(new Set())
  })

  it('the incumbent beats the pure ordering in BOTH directions', () => {
    // Without incumbency the all-zeros MINTED sig wins lexicographically — so
    // the incumbent mirror is the pure-ordering LOSER, which is the only
    // direction in which the incumbency layer can be caught missing. An
    // assertion where the incumbent also won lexicographically would pass with
    // the whole feature deleted.
    expect(preferSitemapId(mirrorSig, mintedSig)).toBe(mintedSig)
    expect(preferSitemapId(mirrorSig, mintedSig, new Set([mintedSig]))).toBe(mintedSig)
    expect(preferSitemapId(mintedSig, mirrorSig, new Set([mintedSig]))).toBe(mintedSig)
    expect(preferSitemapId(mirrorSig, mintedSig, new Set([mirrorSig]))).toBe(mirrorSig)
    expect(preferSitemapId(mintedSig, mirrorSig, new Set([mirrorSig]))).toBe(mirrorSig)
  })

  it('outranks the sig-class layer — a 24-hex incumbent keeps its URL', () => {
    const sig24 = `sig_${'a'.repeat(24)}`
    const sig32 = `sig_${'b'.repeat(32)}`
    expect(preferSitemapId(sig24, sig32)).toBe(sig32)
    expect(preferSitemapId(sig24, sig32, new Set([sig24]))).toBe(sig24)
  })

  it('falls through to the pure ordering when both or neither are incumbents', () => {
    expect(preferSitemapId(mirrorSig, mintedSig, new Set())).toBe(mintedSig)
    expect(preferSitemapId(mirrorSig, mintedSig, new Set([mirrorSig, mintedSig]))).toBe(mintedSig)
    // An unrelated incumbent must not tip a comparison it isn't part of.
    expect(preferSitemapId(mirrorSig, mintedSig, new Set(['sig_unrelated']))).toBe(mintedSig)
    // Non-Set arguments are ignored rather than thrown on.
    expect(preferSitemapId(mirrorSig, mintedSig, undefined)).toBe(mintedSig)
    expect(preferSitemapId(mirrorSig, mintedSig, null)).toBe(mintedSig)
    expect(preferSitemapId(mirrorSig, mintedSig, {})).toBe(mintedSig)
  })

  it('is a total order, so the pairwise fold is independent of feed page order', () => {
    // collectSitemapProducts folds candidates pairwise in arrival order. A
    // preference that is not a total order would make the winner depend on
    // backend pagination order — i.e. churn between runs from an unchanged
    // catalog, the exact thing incumbency exists to stop.
    const a = `sig_${'1'.repeat(32)}`
    const b = `sig_${'2'.repeat(24)}`
    const c = `sig_${'3'.repeat(32)}`
    const incumbents = new Set([b])
    const fold = (ids) => ids.reduce((acc, id) => preferSitemapId(acc, id, incumbents))
    const permutations = [
      [a, b, c], [a, c, b], [b, a, c], [b, c, a], [c, a, b], [c, b, a],
    ]
    for (const order of permutations) expect(fold(order)).toBe(b)
  })

  it('mergeDuplicateProduct threads the incumbent set through', () => {
    const mirror = { id: mirrorSig, contentKey: 'ck_p3', lastmod: new Date('2026-06-30T00:00:00Z') }
    const minted = { id: mintedSig, contentKey: 'ck_p3', lastmod: new Date('2026-07-17T00:00:00Z') }
    // Pin the direction the pure ordering would get WRONG: mirrorSig loses
    // lexicographically, so it can only win here if the set is threaded.
    const merged = mergeDuplicateProduct(mirror, minted, new Set([mirrorSig]))
    expect(merged.id).toBe(mirrorSig)
    // lastmod still merges to the max regardless of which id won.
    expect(merged.lastmod).toEqual(new Date('2026-07-17T00:00:00Z'))
    expect(mergeDuplicateProduct(mirror, minted, new Set([mintedSig])).lastmod).toEqual(
      new Date('2026-07-17T00:00:00Z'),
    )
  })

  it('unescapes before decoding, so an apostrophe in an id still matches itself', () => {
    // Two writers run on the way out: productUrlEntries percent-encodes the id,
    // then buildSitemapUrlsetXml escapes the <loc>. encodeURIComponent leaves
    // `'` alone, so escapeXml is the one that touches it — and if the parse only
    // undoes the percent-encoding, the id comes back as sig_a&apos;b and never
    // matches its own product again.
    const xml = buildSitemapUrlsetXml(productUrlEntries([{ id: "sig_a'b", lastmod: null }]))
    expect(xml).toContain('&apos;')
    expect(parseSitemapProductIds(xml)).toEqual(new Set(["sig_a'b"]))
  })

  it('an already-escaped ampersand survives the round-trip (&amp; unescapes last)', () => {
    const xml = buildSitemapUrlsetXml(productUrlEntries([{ id: 'sig_a&lt;b', lastmod: null }]))
    expect(parseSitemapProductIds(xml)).toEqual(new Set(['sig_a&lt;b']))
  })
})

describe('collectSitemapProducts — backend pagination', () => {
  beforeEach(() => {
    vi.stubEnv('PIVOTA_BACKEND_BASE_URL', 'https://canonical.example.com')
  })

  afterEach(() => {
    vi.restoreAllMocks()
    vi.unstubAllEnvs()
  })

  it('paginates canonical products until the endpoint is exhausted and dedupes', async () => {
    const firstPage = products(1000, 'sig_page_one')
    const secondPage = [canonicalProduct('sig_page_two_0000'), canonicalProduct('sig_page_one_0000')]
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const offset = new URL(String(input)).searchParams.get('offset')
      return pageResponse(offset === '0' ? firstPage : secondPage, 1002, Number(offset || 0))
    })

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(2)
    expect(new URL(String(fetchMock.mock.calls[0][0])).searchParams.get('offset')).toBe('0')
    expect(new URL(String(fetchMock.mock.calls[1][0])).searchParams.get('offset')).toBe('1000')
    const fetchedUrl = new URL(String(fetchMock.mock.calls[0][0]))
    expect(fetchedUrl.pathname).toBe('/api/canonical/products')
    expect(fetchedUrl.searchParams.get('limit')).toBe('1000')
    // duplicate sig_page_one_0000 dropped
    expect(collected).toHaveLength(1001)
    expect(source).toBe('serving_eligible')
    const ids = collected.map((p) => p.id)
    expect(ids).toContain('sig_page_one_0000')
    expect(ids).toContain('sig_page_two_0000')
    // deterministic output: sorted by id regardless of backend order
    expect(ids).toEqual([...ids].sort())
  })

  it('emits ONE url when multiple sigs share a content_key (multi-sig product)', async () => {
    const sig24 = `sig_${'1'.repeat(24)}`
    const sig32 = `sig_${'2'.repeat(32)}`
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse(
        [
          { sig_id: sig24, content_key: 'ck_same_product', serving_eligible: true, updated_at: '2026-01-01T00:00:00.000Z' },
          { sig_id: sig32, content_key: 'ck_same_product', serving_eligible: true, updated_at: '2026-06-01T00:00:00.000Z' },
          canonicalProduct('sig_other_product'),
        ],
        3,
      ),
    )

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected).toHaveLength(2)
    const dup = collected.find((p) => p.contentKey === 'ck_same_product')
    expect(dup?.id).toBe(sig32) // deterministic winner: longer sig class
    expect(dup?.lastmod).toEqual(new Date('2026-06-01T00:00:00.000Z'))
    expect(source).toBe('serving_eligible')
  })

  it('reports serving_eligible_partial when rows are filtered out', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse([canonicalProduct('sig_keep_me'), { sig_id: 'ext_alias' }], 2),
    )

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected.map((p) => p.id)).toEqual(['sig_keep_me'])
    expect(source).toBe('serving_eligible_partial')
  })

  it('renderable=false drops do NOT mark the run partial (expected filter, not anomaly)', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse(
        [
          canonicalProduct('sig_keep_me'),
          { ...canonicalProduct('sig_dead_pdp'), renderable: false },
        ],
        2,
      ),
    )

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected.map((p) => p.id)).toEqual(['sig_keep_me'])
    expect(source).toBe('serving_eligible')
  })

  it('ck-only drops do NOT mark the run partial (well-formed row, not a parse failure)', async () => {
    // Mirrors the renderable=false case above. ck-only rows are now rejected by
    // readCanonicalProduct (their /products/{ck} URL 500s), but they are valid
    // rows — if they counted as "invalid" the source label would read
    // serving_eligible_partial on EVERY regeneration for as long as the feed
    // contains one, permanently retiring the anomaly signal for real parse
    // failures.
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse(
        [
          canonicalProduct('sig_keep_me'),
          { sig_id: null, content_key: 'ck_storeless_brand', index_eligible: true },
        ],
        2,
      ),
    )

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected.map((p) => p.id)).toEqual(['sig_keep_me'])
    expect(source).toBe('serving_eligible')
  })

  it('a genuinely malformed row STILL marks the run partial', async () => {
    // The signal must survive: garbage rows are the thing _partial exists for.
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse([canonicalProduct('sig_keep_me'), 'not-an-object'], 2),
    )

    const { source } = await collectSitemapProducts('https://canonical.example.com')
    expect(source).toBe('serving_eligible_partial')
  })

  it('pages by keyset cursor when the backend provides next_cursor', async () => {
    const firstPage = products(1000, 'sig_cursor_one')
    const secondPage = [canonicalProduct('sig_cursor_two_0000')]
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const url = new URL(String(input))
      if (url.searchParams.get('cursor') === 'opaque-cursor-1') {
        return pageResponse(secondPage, null, 0, { has_more: false, next_cursor: null })
      }
      return pageResponse(firstPage, 1001, 0, {
        has_more: true,
        next_cursor: 'opaque-cursor-1',
      })
    })

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(2)
    const firstUrl = new URL(String(fetchMock.mock.calls[0][0]))
    expect(firstUrl.searchParams.get('offset')).toBe('0')
    expect(firstUrl.searchParams.get('cursor')).toBeNull()
    const secondUrl = new URL(String(fetchMock.mock.calls[1][0]))
    expect(secondUrl.searchParams.get('cursor')).toBe('opaque-cursor-1')
    // Cursor and offset are mutually exclusive on the backend.
    expect(secondUrl.searchParams.get('offset')).toBeNull()
    expect(collected).toHaveLength(1001)
    expect(source).toBe('serving_eligible')
  })

  it('stops on has_more=false even when the page is full and total is null', async () => {
    // New backend, catalog exactly one page: total present only on page one,
    // has_more says stop. The legacy full-page heuristic alone would have
    // issued a wasted second fetch.
    const fetchMock = vi
      .spyOn(globalThis, 'fetch')
      .mockResolvedValueOnce(
        pageResponse(products(1000), 1000, 0, { has_more: false, next_cursor: null }),
      )

    const { products: collected } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(collected).toHaveLength(1000)
  })

  it('falls back to offset paging when next_cursor stops mid-crawl', async () => {
    // Defensive backend path: has_more=true but no cursor. The crawl must
    // continue from the rows already consumed, not restart at offset=0.
    const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const url = new URL(String(input))
      const offset = url.searchParams.get('offset')
      if (offset === '0') {
        return pageResponse(products(1000, 'sig_fb_one'), null, 0, {
          has_more: true,
          next_cursor: null,
        })
      }
      return pageResponse([canonicalProduct('sig_fb_two_0000')], null, 1000, {
        has_more: false,
        next_cursor: null,
      })
    })

    const { products: collected } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(2)
    expect(new URL(String(fetchMock.mock.calls[1][0])).searchParams.get('offset')).toBe('1000')
    expect(collected).toHaveLength(1001)
  })

  it('offset-resume anchor tracks rows consumed, not the nominal page size', async () => {
    // The failure this guards: cursor paging, then next_cursor drops on a
    // SHORT page (fewer items than `limit`) while has_more stays true. The
    // offset fallback must resume at the exact count of rows already consumed
    // (1000 + 400 = 1400), NOT `offset += limit` (which would jump to 2000 and
    // silently skip 600 rows — an undercount small enough to slip past the
    // 50%-shrink guard).
    const calls = []
    vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const url = new URL(String(input))
      const cursor = url.searchParams.get('cursor')
      const offset = url.searchParams.get('offset')
      calls.push({ cursor, offset })
      if (cursor === null && offset === '0') {
        return pageResponse(products(1000, 'sig_anchor_a'), null, 0, {
          has_more: true,
          next_cursor: 'CUR1',
        })
      }
      if (cursor === 'CUR1') {
        // Short page + downgrade: has_more true, no next_cursor.
        return pageResponse(products(400, 'sig_anchor_b'), null, 0, {
          has_more: true,
          next_cursor: null,
        })
      }
      // Resume-by-offset page: the offset it arrives with is the assertion.
      return pageResponse(products(2, 'sig_anchor_c'), null, Number(offset), {
        has_more: false,
        next_cursor: null,
      })
    })

    const { products: collected } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    // Page 3 resumed at rows consumed (1000 + 400), not at offset += limit.
    expect(calls).toHaveLength(3)
    expect(calls[1]).toEqual({ cursor: 'CUR1', offset: null })
    expect(calls[2]).toEqual({ cursor: null, offset: '1400' })
    // Full set collected, no gaps and no duplicates.
    expect(collected).toHaveLength(1402)
    expect(new Set(collected.map((p) => p.id)).size).toBe(1402)
  })

  it('returns an empty set when the endpoint has no products', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(pageResponse([], 0))

    const { products: collected, source } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected).toHaveLength(0)
    expect(source).toBe('serving_eligible')
    const xml = buildSitemapUrlsetXml(productUrlEntries(collected))
    expect(xml).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    expect(xml).not.toContain('<url>')
  })
})

describe('sanity guard — never publish a stub over the full set (#219/#223 lesson)', () => {
  it('refuses counts below the absolute floor', () => {
    expect(sitemapCountGuard(0, null)).toMatch(/absolute floor/)
    expect(sitemapCountGuard(999, null)).toMatch(/absolute floor/)
    expect(sitemapCountGuard(1000, null)).toBeNull()
  })

  it('refuses a large shrink vs the committed count', () => {
    expect(sitemapCountGuard(3000, 7400)).toMatch(/less than 50%/)
    expect(sitemapCountGuard(3700, 7400)).toBeNull()
    expect(sitemapCountGuard(7400, 7400)).toBeNull()
  })

  it('ignores the ratio check when there is no committed file', () => {
    expect(sitemapCountGuard(1200, null)).toBeNull()
  })

  it('counts <loc> entries in existing XML', () => {
    const xml = buildSitemapUrlsetXml(productUrlEntries([
      readCanonicalProduct(canonicalProduct('sig_a')),
      readCanonicalProduct(canonicalProduct('sig_b')),
    ]))
    expect(countLocs(xml)).toBe(2)
  })
})

describe('id guard — never publish a URL that errors (#274 ck_ lesson)', () => {
  it('passes a wholly sig-keyed set', () => {
    const urls = productUrlEntries([
      readCanonicalProduct(canonicalProduct('sig_a')),
      readCanonicalProduct(canonicalProduct('sig_b')),
    ])
    expect(sitemapIdGuard(urls)).toBeNull()
  })

  it('passes an empty set (the count guard owns emptiness)', () => {
    expect(sitemapIdGuard([])).toBeNull()
  })

  it('refuses a ck-keyed URL and names it', () => {
    const violation = sitemapIdGuard([
      { loc: 'https://agent.pivota.cc/products/sig_ok' },
      { loc: 'https://agent.pivota.cc/products/ck_04f8072d8e35a9f1977d67a97daef873' },
    ])
    expect(violation).toMatch(/1 product URL\(s\) are not sig-keyed/)
    expect(violation).toContain('ck_04f8072d8e35a9f1977d67a97daef873')
  })

  it('refuses ext_ and other non-sig prefixes too', () => {
    expect(sitemapIdGuard([{ loc: 'https://agent.pivota.cc/products/ext_1' }])).toMatch(
      /not sig-keyed/,
    )
    expect(sitemapIdGuard([{ loc: 'https://agent.pivota.cc/products/' }])).toMatch(/not sig-keyed/)
  })

  it('is not fooled by a sig_ appearing off the id position', () => {
    // Wrong host, and a path that merely contains "sig_" further along.
    expect(sitemapIdGuard([{ loc: 'https://evil.example/products/sig_a' }])).toMatch(
      /not sig-keyed/,
    )
    expect(sitemapIdGuard([{ loc: 'https://agent.pivota.cc/products/ck_x/sig_a' }])).toMatch(
      /not sig-keyed/,
    )
  })

  it('truncates the sample but reports the full count', () => {
    const urls = Array.from({ length: 9 }, (_, i) => ({
      loc: `https://agent.pivota.cc/products/ck_${i}`,
    }))
    const violation = sitemapIdGuard(urls)
    expect(violation).toMatch(/^9 product URL\(s\)/)
    expect(violation).toContain(', …')
  })

  it('treats malformed entries as violations rather than throwing', () => {
    expect(() => sitemapIdGuard([null, undefined, {}])).not.toThrow()
    expect(sitemapIdGuard([null, undefined, {}])).toMatch(/^3 product URL\(s\)/)
  })

  it('reports non-array input instead of throwing', () => {
    for (const input of [undefined, null, {}, 'abc']) {
      expect(() => sitemapIdGuard(input)).not.toThrow()
      expect(sitemapIdGuard(input)).toMatch(/not an array/)
    }
  })

  it('refuses a bare sig_ with no id body', () => {
    // /products/sig_ errors exactly like a ck_ URL, and it passes a naive
    // startsWith — so the guard checks length as well as prefix.
    expect(sitemapIdGuard([{ loc: 'https://agent.pivota.cc/products/sig_' }])).toMatch(
      /not sig-keyed/,
    )
    expect(sitemapIdGuard([{ loc: 'https://agent.pivota.cc/products/sig_a' }])).toBeNull()
  })
})

describe('readCanonicalProduct rejects a degenerate sig_ (keeps the un-forceable guard unreachable)', () => {
  it('drops a row whose sig_id is a bare prefix', () => {
    // If this row survived, it would reach sitemapIdGuard — which SITEMAP_FORCE
    // cannot bypass — and wedge the cron red with no escape hatch. Drop it here
    // instead, where one bad row just costs one URL.
    expect(
      readCanonicalProduct({ sig_id: 'sig_', content_key: 'ck_x', serving_eligible: true }),
    ).toBeNull()
    expect(
      readCanonicalProduct({ sig_id: '  sig_  ', content_key: 'ck_x', serving_eligible: true }),
    ).toBeNull()
  })

  it('still accepts a normal sig', () => {
    const row = readCanonicalProduct(canonicalProduct('sig_abc123'))
    expect(row).not.toBeNull()
    expect(row.id).toBe('sig_abc123')
  })
})

describe('deterministic observability comment', () => {
  it('embeds source and count as an XML comment after the declaration', () => {
    const xml = buildSitemapUrlsetXml(
      productUrlEntries([readCanonicalProduct(canonicalProduct('sig_a'))]),
      'source=serving_eligible urls=1',
    )

    expect(xml).toMatch(
      /^<\?xml version="1\.0" encoding="UTF-8"\?>\n<!-- source=serving_eligible urls=1 -->\n<urlset/,
    )
  })
})

// The production feed's exact shape, and the reason these tests exist:
// GET /api/canonical/products answers `total` on the FIRST page only —
// offset>0 and cursor pages both return `total: null` — while `has_more` is
// present on every page. Verified against prod 2026-07-25 (6 pages, 5,887
// rows). A paging chain that mistakes that absent `total` for a real 0 caps
// the walk at one page and publishes a fraction of the catalog.
describe('collectSitemapProducts — `total` present on the first page only (prod shape)', () => {
  beforeEach(() => {
    vi.stubEnv('PIVOTA_BACKEND_BASE_URL', 'https://canonical.example.com')
    vi.spyOn(console, 'log').mockImplementation(() => {})
    vi.spyOn(console, 'warn').mockImplementation(() => {})
  })

  afterEach(() => {
    vi.restoreAllMocks()
    vi.unstubAllEnvs()
  })

  // Pages the way prod does: real `total` on page 1, `total: null` after.
  function firstPageOnlyTotalFetch(pagesByOffset, grandTotal, { withHasMore }) {
    return vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
      const offset = Number(new URL(String(input)).searchParams.get('offset') || 0)
      const items = pagesByOffset[offset] ?? []
      const consumed = offset + items.length
      const body = {
        items,
        total: offset === 0 ? grandTotal : null,
        limit: 1000,
        offset,
      }
      if (withHasMore) body.has_more = consumed < grandTotal
      return new Response(JSON.stringify(body), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      })
    })
  }

  it('walks every page when has_more is present (the arm prod actually uses)', async () => {
    const fetchMock = firstPageOnlyTotalFetch(
      {
        0: products(1000, 'sig_p1'),
        1000: products(1000, 'sig_p2'),
        2000: products(500, 'sig_p3'),
      },
      2500,
      { withHasMore: true },
    )

    const { products: collected, source, coverage } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(3)
    expect(collected).toHaveLength(2500)
    expect(source).toBe('serving_eligible')
    expect(coverage).toMatchObject({ rowsSeen: 2500, feedTotal: 2500, stoppedForCap: false })
    expect(sitemapCoverageGuard(coverage)).toBeNull()
  })

  // THE REGRESSION FENCE. Strip has_more and the walk must fall through to the
  // items-length heuristic. It only can if an absent `total` stays null:
  // `Number(null)` is 0, 0 is finite, and `0 < 0` is false, so a bare Number()
  // coercion yields total=0 — `offset < 0` is then always false and this stops
  // after page 2 with 2,000 of 2,500 rows, silently.
  it('falls back to the items-length heuristic when BOTH has_more and total are absent', async () => {
    const fetchMock = firstPageOnlyTotalFetch(
      {
        0: products(1000, 'sig_p1'),
        1000: products(1000, 'sig_p2'),
        2000: products(500, 'sig_p3'),
      },
      2500,
      { withHasMore: false },
    )

    const { products: collected, coverage } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(collected).toHaveLength(2500)
    expect(coverage.rowsSeen).toBe(2500)
    // Three pages exactly — the short final page terminates the walk; it must
    // not fetch a fourth, empty page.
    expect(fetchMock).toHaveBeenCalledTimes(3)
    expect(fetchMock.mock.calls.map((call) => new URL(String(call[0])).searchParams.get('offset')))
      .toEqual(['0', '1000', '2000'])
  })

  it('uses `offset < total` on page 1 to stop without a wasted fetch', async () => {
    // Isolates the middle arm. The page is FULL (1000 == limit), so the
    // items-length heuristic alone would fetch a second, empty page; the
    // page-1 `total` is what makes this a single-fetch walk. This only works
    // on page 1 — `total` is unknown from page 2 on, by design of the feed.
    const fetchMock = firstPageOnlyTotalFetch({ 0: products(1000, 'sig_p1') }, 1000, {
      withHasMore: false,
    })

    const { products: collected, coverage } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(collected).toHaveLength(1000)
    expect(coverage).toMatchObject({ rowsSeen: 1000, feedTotal: 1000 })
    expect(sitemapCoverageGuard(coverage)).toBeNull()
  })

  it('terminates on an empty page when a has_more-less walk ends on a full page', async () => {
    // Documents the cost of losing has_more: with `total` unknown after page 1
    // and a final page exactly `limit` wide, the heuristic cannot tell "done"
    // from "more", so it spends one extra empty fetch to find out. Correct,
    // just not free — and it must still terminate rather than loop.
    const fetchMock = firstPageOnlyTotalFetch(
      { 0: products(1000, 'sig_p1'), 1000: products(1000, 'sig_p2') },
      2000,
      { withHasMore: false },
    )

    const { products: collected, coverage } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(fetchMock).toHaveBeenCalledTimes(3)
    expect(collected).toHaveLength(2000)
    // The empty third page adds no rows, so coverage still reconciles.
    expect(coverage.rowsSeen).toBe(2000)
    expect(sitemapCoverageGuard(coverage)).toBeNull()
  })

  it('accounts for every consumed row in the drop funnel', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse(
        [
          canonicalProduct('sig_kept_one'),
          canonicalProduct('sig_kept_two'),
          // dead: explicitly non-renderable
          { ...canonicalProduct('sig_dead'), renderable: false },
          // merged: same content_key as sig_kept_one
          { sig_id: 'sig_kept_one_dupe', content_key: 'ck_kept_one', serving_eligible: true },
          // malformed / ineligible
          { sig_id: 'ext_alias' },
        ],
        5,
        0,
        { has_more: false },
      ),
    )

    const { products: collected, coverage } = await collectSitemapProducts(
      'https://canonical.example.com',
    )

    expect(coverage.rowsSeen).toBe(5)
    expect(coverage.dropped).toEqual({
      dead: 1,
      mergedDuplicate: 1,
      notEligibleOrMalformed: 1,
    })
    // rowsSeen reconciles exactly: 5 rows = 2 URLs + 1 + 1 + 1 dropped.
    const totalDropped =
      coverage.dropped.dead +
      coverage.dropped.mergedDuplicate +
      coverage.dropped.notEligibleOrMalformed
    expect(collected.length + totalDropped).toBe(coverage.rowsSeen)
  })

  it('reports feedTotal as null (not 0) when the backend never sends a total', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      pageResponse(products(3), null, 0, { has_more: false }),
    )

    const { coverage } = await collectSitemapProducts('https://canonical.example.com')

    // Null, never 0 — 0 would read as "the feed has no products", and would
    // make the coverage guard pass vacuously on a truncated walk.
    expect(coverage.feedTotal).toBeNull()
    expect(sitemapCoverageGuard(coverage)).toBeNull()
  })
})

describe('coverage guard — rows consumed vs rows the feed promised', () => {
  it('passes a walk that consumed every promised row', () => {
    expect(
      sitemapCoverageGuard({ rowsSeen: 5887, feedTotal: 5887, stoppedForCap: false }),
    ).toBeNull()
  })

  it('refuses a walk that stopped early, naming both counts', () => {
    const violation = sitemapCoverageGuard({
      rowsSeen: 2000,
      feedTotal: 5887,
      stoppedForCap: false,
    })
    expect(violation).toContain('2000')
    expect(violation).toContain('5887')
    expect(violation).toContain('34.0%')
  })

  it('tolerates a handful of rows deleted mid-walk (concurrent catalog churn)', () => {
    expect(
      sitemapCoverageGuard({ rowsSeen: 5850, feedTotal: 5887, stoppedForCap: false }),
    ).toBeNull()
    expect(
      sitemapCoverageGuard({ rowsSeen: 5800, feedTotal: 5887, stoppedForCap: false }),
    ).not.toBeNull()
  })

  it('skips when the backend reported no total (nothing to compare against)', () => {
    expect(
      sitemapCoverageGuard({ rowsSeen: 10, feedTotal: null, stoppedForCap: false }),
    ).toBeNull()
  })

  it('skips a legitimate short read at the 50k URL cap', () => {
    expect(
      sitemapCoverageGuard({ rowsSeen: 50000, feedTotal: 90000, stoppedForCap: true }),
    ).toBeNull()
  })

  it('is not fooled by a feedTotal of 0 vs a missing one', () => {
    expect(sitemapCoverageGuard({ rowsSeen: 0, feedTotal: 0, stoppedForCap: false })).toBeNull()
  })

  it('reports missing bookkeeping instead of passing silently', () => {
    expect(sitemapCoverageGuard({ feedTotal: 100, stoppedForCap: false })).toContain('rowsSeen')
    expect(sitemapCoverageGuard()).toBeNull()
  })
})
