// THE DEMO BUYER'S USER TOKEN (`X-Agent-User-JWT`), minted by this UI's server.
//
// Why a token at all. The gateway's Reap lane and the backend rail both need TWO credentials: the
// calling agent's API key and a user token naming the buyer (PIVOTA-Agent docs/reap-agentic-lane.md
// §3, §6; pivota-backend docs/reap_agentic_routes.md "Authentication"). Without the user token the
// lane is skipped silently and the buyer gets the storefront answer. This storefront has no buyer
// identity the gateway could verify, so for the demo the UI server acts as the buyer-token issuer:
//
//   - one RS256 key pair, generated by Peng with scripts/reap-demo-keygen.mjs; the PRIVATE key is
//     only ever in this server's env (REAP_DEMO_USER_JWT_PRIVATE_KEY), the PUBLIC JWKS is what the
//     gateway and backend are configured to trust (docs/reap-checkout-demo.md);
//   - `sub` = an opaque random id this server sets in an HttpOnly cookie on the buyer's browser, so
//     the same browser is the same buyer across create and every poll (the backend answers a
//     purchase only to the buyer that opened it);
//   - `sid` = the same id (the gateway's USER_AUTH_REQUIRED rule wants a session claim);
//   - short-lived (5 minutes), minted per request, never sent to the browser.
//
// No email, name or address goes in the token; the buyer's details travel in the create body only.
import { createPrivateKey, createPublicKey, randomBytes, sign, type KeyObject } from 'node:crypto';

export const REAP_DEMO_BUYER_COOKIE = 'pv_reap_demo_buyer';
const BUYER_ID_RE = /^rdb_[A-Za-z0-9_-]{22,64}$/;
const TOKEN_TTL_SECONDS = 300;

export type BuyerTokenConfig = {
  privateKey: KeyObject;
  kid: string;
  issuer: string;
  audience: string;
};

export class BuyerTokenConfigError extends Error {}

function b64url(input: Buffer | string): string {
  return Buffer.from(input).toString('base64url');
}

/** The issuer config from env, or null when any piece is missing (the route then answers 503). */
export function readBuyerTokenConfig(env: NodeJS.ProcessEnv = process.env): BuyerTokenConfig | null {
  const pem = String(env.REAP_DEMO_USER_JWT_PRIVATE_KEY || '').replace(/\\n/g, '\n').trim();
  const kid = String(env.REAP_DEMO_USER_JWT_KID || '').trim();
  const issuer = String(env.REAP_DEMO_USER_JWT_ISSUER || '').trim();
  const audience = String(env.REAP_DEMO_USER_JWT_AUDIENCE || '').trim();
  if (!pem || !kid || !issuer || !audience) return null;
  let privateKey: KeyObject;
  try {
    privateKey = createPrivateKey(pem);
  } catch {
    return null;
  }
  if (privateKey.asymmetricKeyType !== 'rsa') return null;
  return { privateKey, kid, issuer, audience };
}

export function newBuyerId(): string {
  return `rdb_${randomBytes(24).toString('base64url')}`;
}

export function isBuyerId(value: unknown): value is string {
  return typeof value === 'string' && BUYER_ID_RE.test(value);
}

export function mintBuyerToken(
  config: BuyerTokenConfig,
  buyerId: string,
  nowSeconds: number = Math.floor(Date.now() / 1000),
): string {
  if (!isBuyerId(buyerId)) throw new BuyerTokenConfigError('invalid buyer id');
  const header = { alg: 'RS256', typ: 'JWT', kid: config.kid };
  const payload = {
    iss: config.issuer,
    aud: config.audience,
    sub: buyerId,
    sid: buyerId,
    iat: nowSeconds,
    nbf: nowSeconds - 5,
    exp: nowSeconds + TOKEN_TTL_SECONDS,
    jti: randomBytes(12).toString('base64url'),
  };
  const signingInput = `${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(payload))}`;
  const signature = sign('RSA-SHA256', Buffer.from(signingInput), config.privateKey);
  return `${signingInput}.${b64url(signature)}`;
}

/** The PUBLIC half as a JWKS — what the gateway and backend are configured to trust. */
export function publicJwks(config: BuyerTokenConfig): { keys: Array<Record<string, string>> } {
  const jwk = createPublicKey(config.privateKey).export({ format: 'jwk' }) as Record<string, string>;
  return { keys: [{ kty: jwk.kty, n: jwk.n, e: jwk.e, kid: config.kid, alg: 'RS256', use: 'sig' }] };
}
